добавлен Context
Tahora/react-burger pull request #3
Opened 2022-11-22 21:45 UTC by Tahora

2022-11-23 04:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Реализована работа с контекстом.

### **Но есть несколько замечаний, которые нужно исправить:**

- При отправке запроса на создание заказа `POST /orders`, в поле `ingredients` следует передавать обе булки, а не 1. Т.е. id булок должны быть в самом начале массива, и в конце, а также они должны быть одинаковы;

- У вас неправильно считается цена, https://yadi.sk/d/DcrZkZh-DQVdUw. В каких-то случаев она считается нормально, а в каких-то нет.

- По макету, в компоненте App-header нужно чтобы была активна только 1 ссылка.

- Исправить ошибку в консоли: https://yadi.sk/d/JEjFT55o0jGmdw;

- Структуру ингредиента лучше описать таким образом:

  ```js
  export const ingredientPropType = PropTypes.shape({
    _id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    calories: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
    image: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
  });
  ```

  А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
  Пример как правильно:

  ```js
  // массив
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;

  // одиночный элемент
  data: ingredientTypes.isRequired;
  ```

  И в описании propTypes компонентов нужно указывать .isRequired у пропсов (Если это требуется), без этого не контролируется, что пропс передается

  Проверьте во всем проекте.

### **Сделает код лучше:**

- лучше всегда использовать строгое сравнение `===` и строгое неравенство `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

- не стоит в обработчика событий использовать двойные функции. Если вам нужно передать какой-то параметр используйте анонимные функции.

  ```jsx
  const handleClick = (param) => {
    /** ... */
  };

  <Component onClick={() => handleClick(param)} />;
  ```

- при клике на таб скролить список ингредиентов к нужному разделу.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/app/app.js
> +            getData(getIngridients, null, ingridientsState);
**Надо исправить:**

Функция должна выполнять только 1 действие, и функции получения данных с сервера, точно не стоит знать о каких-либо стейтах, это плохая практика. Функция должна возвращать результат выполнения запроса, а вы уже потом делаете с ним что нужно.

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +    const total = (bun, items) => {
**Можно лучше:**

Лучше обернуть в `useMemo`. Чтобы не было перерасчёта после ререндеров.

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +        return i.type == "bun"
**Можно лучше:**

Здесь и далее.

лучше всегда использовать строгое сравнение `===` и строгое неравенство `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +    const bun = allbuns[Math.floor(Math.random() * allbuns.length)];
**Можно лучше:**

Для того чтобы вытащить булку, рекомендую использовать метод `find`.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +    }, [JSON.stringify(mainItems)]);
**Надо исправить:**

Не стоит тут использовать `JSON.stringify`. JSON.stringify, можно использовать если вы знаете что у вас не будет сложных структур данных, а также малое количество элементов. Рекомендую пока вообще отказаться от глубокого сравнения, здесь этого не требуется. 

https://github.com/facebook/react/issues/14476#issuecomment-471199055

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +                <OrderTotal total={stateTotal} showModal={showModal([...mainItems.map((i) => {
**Надо исправить:**

Вынесите обработчик событий в отдельную функцию. И там уже делайте манипулируйте с данными.

**Можно лучше:**

А также, не стоит в обработчика событий использовать двойные функции. Если вам нужно передать какой-то параметр используйте анонимные функции.

```js

const handleClick = (param) => {/** ... */}

<Component onClick = {() => handleClick(param)} />

```

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +                (<OrderContext.Provider value={orderState}>
**Можно лучше:**

Не стоит ради 1 компонента создавать контекст.

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +        let itemsArray = [];
**Можно лучше:**

если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerIngredients/burgerIngredients.js
>                  <div className={`${styles.ingridientsTable} pl-4 pr-4`}>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-11-23 04:43 UTC, ArslanDev666 commented on src/components/burgerIngredients/burgerIngredients.js
> +                    {burgerdata.filter((i) => {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2022-11-23 04:43 UTC, ArslanDev666 commented on src/utils/api.js
> +            })();
**Надо исправить:** Не стоит использовать тут IIFE, просто сделайте условие не через тернарный оператор, а через if.

2022-11-27 22:45 UTC, Tahora commented on src/components/burgerConstructor/burgerConstructor.js
> +    const total = (bun, items) => {
функция обернута в редьюсер, и вызывется в  useEffect только при  первом рендере.  Разве это не гарантирует, что её расчёт будет проводиться только один раз?

function reducer(state, action) {
        return total(action.bun, action.items);
    }

 const [stateTotal, dispatch] = useReducer(reducer, 0);
    useEffect(() => {
        dispatch({bun: bun, items: mainItems});
    }, []);

2022-11-27 23:01 UTC, Tahora commented on src/components/burgerConstructor/burgerConstructor.js
> +    const bun = allbuns[Math.floor(Math.random() * allbuns.length)];
тогда всегда будет одна и та же булка. Filter  выбран, что бы иметь возможность для тестирования рандомно выбирать любую из доступных булок

2022-11-28 03:11 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +    const bun = allbuns[Math.floor(Math.random() * allbuns.length)];
Ну так нам пока необязательно чтобы булки менялись каждый раз) ну и плюс всё равно в будущем это всё будет происходить через DnD_ . В любом случае, это замечание не обязательно к исправлению.

2022-11-28 03:16 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +    const total = (bun, items) => {
Всё верно, что-то я перепутал)) думал что это просто переменная, ну не суть.
Тогда лучше вообще эту функцию вынести в утилиты, ибо при каждом ререндере пересоздается ссылка на функцию)) А редьюсер лучше вынести за пределы компонента, по той же причине.

2022-11-29 02:46 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята. Можете приступать к выполнению следующего задания. Удачи в дальнейшем обучении.**

- Все замечания с прошлого ревью были исправлены.

### **Но есть несколько замечаний, которые лучше исправить перед выполнением следующего задания:**

- По макету, у хедера есть свой фон, а также он чуть выше должен быть.

  - как у вас: https://yadi.sk/d/T49kS4KJ3K-fMQ;
  - как в макете: https://yadi.sk/d/yUx0SBn5HAiofA;

### **Сделает код лучше:**

- при клике на таб скролить список ингредиентов к нужному разделу.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-29 02:46 UTC, ArslanDev666 commented on src/utils/api.js
> +export const loadDataToState = async (callbackApi, paramsApi, callbackState) => {
**Можно лучше:**

Не стоит таким образом менять стейт. Лучше всего стейт менять после получения данных с сервера, и делать это в самом компоненте, а не где-то в коллбэках.

2022-11-29 02:46 UTC, ArslanDev666 commented on src/components/burgerConstructor/burgerConstructor.js
> +  }, []);
**Надо исправить:**

Здесь и далее.
У вас не будет происходить фильтрация, если вы оставите массив зависимостей пустым. Вам лучше передать туда `items.data.data` (и ещё я бы уменьшил как-нибудь эту надпись) нужно смотреть в сторону присвоение контексту значения)

2022-12-10 21:26 UTC, merged