month9/step2
Tahora/react-burger pull request #6
Opened 2023-04-03 09:17 UTC by Tahora

2023-04-03 13:37 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную работу по добавлению новых экранов в ваш проект, удобно реализовали подключение к сокетам, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- При прямом переходе на маршрут заказа пользователя `/profile/orders/:id` следует открывать страницу заказа или модальное окно (по выбору);
- Следует реализовать скролл к выбранному разделу по нажатию на таб в конструкторе (согласно условиям из предыдущих заданий);
- Следует именовать хуки в формате `camelCase`, например `useOrderInfo` (с маленькой буквы);
- В массиве зависимостей следует указывать переменные, не нужно преобразовывать их с помощью `stringify`;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- В каждой из колонок с номерами заказов можно положить до 10 записей, чтобы уменьшить необходимость в горизонтальном скроллинге;
- Во время отсутствия данных в модальном окне отображается `#undefined`, для удобства пользователя лучше временно скрывать такие данные;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-04-03 13:37 UTC, randomroot commented on src/components/olders-list/orders-list.js
> +                style={{ textDecoration: "none", color: "#F2F2F3" }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-04-03 13:37 UTC, randomroot commented on src/components/app/app.js
> +                  {" "}
🟡 **Можно улучшить:**

Рекомендуется проверить настройки форматирования вашего кода, т.к. данные пробелы являются излишними

2023-04-03 13:37 UTC, randomroot commented on src/components/app/app.js
> +                  hideFunction={() => {
🟡 **Можно улучшить:**

Функцию можно вынести в отдельную переменную и переиспользовать её ниже

2023-04-03 13:37 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +    const ingredients = bun?._id
🟡 **Можно улучшить:**

Обратите внимание, что заказы следует формировать как минимум с двумя булками, ибо без них некуда будет класть ингредиенты :)

2023-04-03 13:37 UTC, randomroot commented on src/components/order-view/components/ingredient-icon.js
> +  return t;
🟡 **Можно улучшить:**

В данном случае использование дополнительной переменной излишне, т.к. вы сразу возвращаете результат

2023-04-03 13:37 UTC, randomroot commented on src/middleware/socket-middleware.js
> +          socket.close(1000, "закрыто клиентом");
🟡 **Можно улучшить:**

Целесообразно выносить "магические" числа в отдельную константу, чтобы можно было удобно и просто определить, что они означают.

2023-04-03 13:37 UTC, randomroot commented on src/components/ws-connector/ws-connector.js
> +export function WsConnector(props) {
🟢 **Отлично:**

Интересное решение по подключению сокетов 👍

2023-04-03 13:37 UTC, randomroot commented on src/components/order-view/order-view-detailed.js
> +  console.log(`OrderViewDetailed rendered`);
🟡 **Можно улучшить:**

Целесообразно убрать логгирование, используемое на этапе разработки и отладки, чтобы уменьшить кол-во информации, которое выводится в консоль :)

2023-04-03 13:37 UTC, randomroot commented on src/hooks/use-order-info.js
> +export function UseOrderInfo(orderId) {
🔴 **Нужно исправить:**

Название хукам следует давать с в формате `camelCase` в формате `useAction`, т.к. это не Реакт компонент

2023-04-03 13:37 UTC, randomroot commented on src/hooks/use-order-info.js
> +  }, [JSON.stringify(ingredients)]);
🔴 **Нужно исправить:**

В данном случае достаточно передать массив `ingredients`, не следует его принудительно преобразовывать в строку

2023-04-03 13:37 UTC, randomroot commented on src/hooks/use-order-info.js
> +  const total = useCallback(() => {
🟡 **Можно улучшить:**

В данном случае лучше применить хук `useMemo`, чтобы не производить расчет несколько раз, вызывая функцию, а просто сразу забирать результат

2023-04-03 16:24 UTC, Tahora commented
не совсем поняла замечание: "При прямом переходе на маршрут заказа пользователя /profile/orders/:id следует открывать страницу заказа или модальное окно (по выбору);" 
Имеется в виду что этот роут не является защищённым и открывается даже неавторизованным пользователям?

2023-04-03 16:27 UTC, randomroot commented
> не совсем поняла замечание: "При прямом переходе на маршрут заказа пользователя /profile/orders/:id следует открывать страницу заказа или модальное окно (по выбору);" Имеется в виду что этот роут не является защищённым и открывается даже неавторизованным пользователям?

Добрый день, подразумевается, что если открыть в новой вкладке такой путь, то должна открываться такая страница или окно, по аналогии с лентой заказов. В данный момент если пользователь авторизован и попытается в новом окне открыть такой путь он попадет просто на свою историю заказов

2023-04-03 19:11 UTC, Tahora commented
не могу воспроизвести ошибку с путём /profile/orders/:id    
у меня получается если пользователь не авторизован - сначала экран логина, а после него открывается детализация запрошенного заказа (одного) .
Если несуществующий номер заказа передан - пустой экран. 
Может быть вы можете что-то посоветовать?

2023-04-04 07:03 UTC, randomroot requested changes
**Здравствуйте!**

Вы **успешно** внесли множество изменений и улучшений в ваш проект, так держать!

Осталось **поправить** только момент с открытием страницы с информацией о заказе пользователя. Для этого рекомендую вам отображать **отдельную страницу** (где будут видны только хедер и информация о заказе), а получать инфу можно как из сокета, так и напрямую, т.к. для этого есть **удобный API метод** `https://norma.nomoreparties.space/api/orders/{id}` (возможно не упомянутый в рамках теории).

_Пример такого экрана_: https://disk.yandex.ru/i/aeyXtkyxKApKJw

Описанный вами процесс перехода с экрана логина на детализацию заказа в профиле не удается воспроизвести (см. https://disk.yandex.ru/i/9T-2UTtLnyvTLA)

**Хорошего вам дня и настроения!** 🐈

2023-04-04 07:03 UTC, randomroot commented on src/components/order-view/order-view-detailed.js
> +      return (<></>)
🟡 **Можно улучшить:**

В данном случае можно вернуть просто `null`

2023-04-04 07:03 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.js
> +      const scrollToSection=(tabValue)=>
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2023-04-04 07:03 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.js
> +          {modalState === true ? (
🟡 **Можно улучшить:**

Такую проверку можно упростить до `modalState ? ... : ...`

2023-04-04 19:32 UTC, Tahora commented on src/components/burger-constructor/burger-constructor.js
> +          {modalState === true ? (
в случае ошибки переменная хранит сообщение для пользователя. при таком способе проверки всегда будет открываться окно информации о заказе

2023-04-04 19:36 UTC, Tahora commented
Большое спасибо за видео, оно сильно помогло! Я при тестировании всегда вставляла url заказа в новой вкладке, а в этом случае ошибка не возникала

2023-04-05 09:48 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-05-02 01:44 UTC, merged